languageCode = "ja"
languageName = "日本語"
weight = 3
title = "LILLIAN LIU"


[params]
  displayName = "日本語"
  isoCode = "ja"
  rtl = false
  dateFormat = "2006-01-02"
  secondaryLogo = "flower-32x32.png"
  logo = "flower-32x32.png"
  description = "WL website"

[author]
  name = "リリ りゅう"
  image = "lwx-clean.jpeg"
  headline =  "{{< audio src=\"/audio/wenxuan_liu_phonetics.mp3\" >}}"
  links = [ { email = "lwxlillian@gmail.com" }, { github = "https://github.com/Lillian-x" }, { linkedin = "https://www.linkedin.com/in/wenxuanliu/" } ]
