languageCode = "en"
languageName = "English"
weight = 1
title = "LILLIAN LIU"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
secondaryLogo = "flower-32x32.png"
logo = "flower-32x32.png"
description = "WL website"

[author]
name = "Wenxuan Liu"
image = "lwx-clean.jpeg"
headline = "{{< audio src=\"/audio/wenxuan_liu_phonetics.mp3\" >}}"
links = [ { email = "lwxlillian@gmail.com" }, { github = "https://github.com/Lillian-x" }, { linkedin = "https://www.linkedin.com/in/wenxuanliu/" } ]
bio = "Learner | Researcher | Designer"
