[[main]]
none = "none"

[[main]]
name = "ブログ"
url = "/blogs/"
identifier = "NjJXiuQbr3"
weight = 9999

[[main]]
name = "紹介"
url = "/about/"
identifier = "zgDihNbt8k"
weight = 9999

[[footer]]
none = "none"


