[[main]]
none = "none"

[[main]]
name = "项目"
pageRef = "projects"
identifier = "0pXMvkOTV3"
weight = 9999

[[main]]
name = "文档"
pageRef = "blogs"
identifier = "NjJXiuQbr3"
weight = 9999

[[main]]
name = "关于"
pageRef = "about"
identifier = "zgDihNbt8k"
weight = 9999

[[footer]]
none = "none"


